// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SongSearch.Web.Controllers {
    public partial class AccountController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LogIn() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LogIn);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Register() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Register);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ResetPasswordRespond() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordRespond);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string LogIn = "LogIn";
            public readonly string LogOut = "LogOut";
            public readonly string Register = "Register";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string ChangePasswordSuccess = "ChangePasswordSuccess";
            public readonly string UpdateProfile = "UpdateProfile";
            public readonly string ResetPassword = "ResetPassword";
            public readonly string ResetPasswordSuccess = "ResetPasswordSuccess";
            public readonly string ResetPasswordRespond = "ResetPasswordRespond";
            public readonly string Plan = "Plan";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string ChangePassword = "~/Views/Account/ChangePassword.aspx";
            public readonly string ChangePasswordSuccess = "~/Views/Account/ChangePasswordSuccess.aspx";
            public readonly string ctrlContactInfo = "~/Views/Account/ctrlContactInfo.ascx";
            public readonly string LogIn = "~/Views/Account/LogIn.aspx";
            public readonly string LogOut = "~/Views/Account/LogOut.aspx";
            public readonly string Plan = "~/Views/Account/Plan.aspx";
            public readonly string Register = "~/Views/Account/Register.aspx";
            public readonly string ResetPassword = "~/Views/Account/ResetPassword.aspx";
            public readonly string ResetPasswordRespond = "~/Views/Account/ResetPasswordRespond.aspx";
            public readonly string ResetPasswordSuccess = "~/Views/Account/ResetPasswordSuccess.aspx";
            public readonly string UpdateProfile = "~/Views/Account/UpdateProfile.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AccountController: SongSearch.Web.Controllers.AccountController {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult LogIn(SongSearch.Web.LogOnModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogIn);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogIn(SongSearch.Web.LogOnModel model, string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogIn);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("returnUrl", returnUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOut() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOut);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register(string id, string em) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Register);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("em", em);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register(SongSearch.Web.RegisterModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Register);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePassword() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePassword(SongSearch.Web.UpdateProfileModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePasswordSuccess() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePasswordSuccess);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpdateProfile() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpdateProfile);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpdateProfile(SongSearch.Web.UpdateProfileModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpdateProfile);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPassword() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPassword);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPassword(SongSearch.Web.ResetPasswordModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPassword);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPasswordSuccess() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordSuccess);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPasswordRespond(string id, string rc) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordRespond);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("rc", rc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPasswordRespond(SongSearch.Web.ResetPasswordModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordRespond);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Plan() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Plan);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
