// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SongSearch.Web.Controllers {
    public partial class CatalogUploadController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CatalogUploadController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Upload() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Upload);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CatalogUploadController Actions { get { return MVC.CatalogUpload; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "CatalogUpload";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Complete = "Complete";
            public readonly string Upload = "Upload";
            public readonly string UserMediaUpload = "UserMediaUpload";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string ctrlHiddenFormInputs = "~/Views/CatalogUpload/ctrlHiddenFormInputs.ascx";
            public readonly string Index = "~/Views/CatalogUpload/Index.aspx";
            public readonly string Upload = "~/Views/CatalogUpload/Upload.aspx";
            public readonly string wfAddPreviewFiles = "~/Views/CatalogUpload/wfAddPreviewFiles.ascx";
            public readonly string wfAddSongFiles = "~/Views/CatalogUpload/wfAddSongFiles.ascx";
            public readonly string wfEditMetadata = "~/Views/CatalogUpload/wfEditMetadata.ascx";
            public readonly string wfSaveCatalog = "~/Views/CatalogUpload/wfSaveCatalog.ascx";
            public readonly string wfSelectCatalog = "~/Views/CatalogUpload/wfSelectCatalog.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_CatalogUploadController: SongSearch.Web.Controllers.CatalogUploadController {
        public T4MVC_CatalogUploadController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Complete() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Complete);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Upload(int? id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Upload);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Upload(SongSearch.Web.Services.CatalogUploadState state) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Upload);
            callInfo.RouteValueDictionary.Add("state", state);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UserMediaUpload() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UserMediaUpload);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
