// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SongSearch.Web.Controllers {
    public partial class ContentController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ContentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Detail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Detail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Print() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Print);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Save() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Save);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveMetaDataToFile() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SaveMetaDataToFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveMediaFiles() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SaveMediaFiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteTag() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteTag);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ContentController Actions { get { return MVC.Content; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Content";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Detail = "Detail";
            public readonly string Print = "Print";
            public readonly string Edit = "Edit";
            public readonly string Save = "Save";
            public readonly string SaveMetaDataToFile = "SaveMetaDataToFile";
            public readonly string SaveMediaFiles = "SaveMediaFiles";
            public readonly string Delete = "Delete";
            public readonly string DeleteMultiple = "DeleteMultiple";
            public readonly string DeleteTag = "DeleteTag";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string ctrlContentDetail = "~/Views/Content/ctrlContentDetail.ascx";
            public readonly string Detail = "~/Views/Content/Detail.aspx";
            public readonly string Print = "~/Views/Content/Print.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ContentController: SongSearch.Web.Controllers.ContentController {
        public T4MVC_ContentController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Detail(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Detail);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Print(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Print);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Save(SongSearch.Web.Data.Content content, System.Collections.Generic.IList<int> tags, System.Collections.Generic.IDictionary<SongSearch.Web.TagType,string> newTags, System.Collections.Generic.IList<SongSearch.Web.ContentRightViewModel> rights, bool returnData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Save);
            callInfo.RouteValueDictionary.Add("content", content);
            callInfo.RouteValueDictionary.Add("tags", tags);
            callInfo.RouteValueDictionary.Add("newTags", newTags);
            callInfo.RouteValueDictionary.Add("rights", rights);
            callInfo.RouteValueDictionary.Add("returnData", returnData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveMetaDataToFile(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SaveMetaDataToFile);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveMediaFiles(int contentId, System.Collections.Generic.IList<SongSearch.Web.Data.UploadFile> uploadFiles) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SaveMediaFiles);
            callInfo.RouteValueDictionary.Add("contentId", contentId);
            callInfo.RouteValueDictionary.Add("uploadFiles", uploadFiles);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteMultiple() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteMultiple);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteTag(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteTag);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
