// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SongSearch.Web.Controllers {
    public partial class ErrorController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ErrorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController Actions { get { return MVC.Error; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Error";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Problem = "Problem";
            public readonly string NotFound = "NotFound";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _404 = "~/Views/Error/404.aspx";
            public readonly string _500 = "~/Views/Error/500.aspx";
            public readonly string Index = "~/Views/Error/Index.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ErrorController: SongSearch.Web.Controllers.ErrorController {
        public T4MVC_ErrorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(System.Exception exc, string message, string controllerName, string actionName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("exc", exc);
            callInfo.RouteValueDictionary.Add("message", message);
            callInfo.RouteValueDictionary.Add("controllerName", controllerName);
            callInfo.RouteValueDictionary.Add("actionName", actionName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Problem() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Problem);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult NotFound() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.NotFound);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
