// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SongSearch.Web.Controllers {
    public partial class SearchController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SearchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Results() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Results);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult AutoComplete() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.AutoComplete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController Actions { get { return MVC.Search; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Search";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Results = "Results";
            public readonly string AutoComplete = "AutoComplete";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string ctrlBreadcrumb = "~/Views/Search/ctrlBreadcrumb.ascx";
            public readonly string ctrlPager = "~/Views/Search/ctrlPager.ascx";
            public readonly string ctrlSearchOptions = "~/Views/Search/ctrlSearchOptions.ascx";
            public readonly string ctrlSearchResults = "~/Views/Search/ctrlSearchResults.ascx";
            public readonly string ctrlSearchResultsTable = "~/Views/Search/ctrlSearchResultsTable.ascx";
            public readonly string Index = "~/Views/Search/Index.aspx";
            public readonly string Results = "~/Views/Search/Results.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SearchController: SongSearch.Web.Controllers.SearchController {
        public T4MVC_SearchController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Results(System.Collections.Generic.IList<SongSearch.Web.SearchField> f, int? p, int? s, int? o) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Results);
            callInfo.RouteValueDictionary.Add("f", f);
            callInfo.RouteValueDictionary.Add("p", p);
            callInfo.RouteValueDictionary.Add("s", s);
            callInfo.RouteValueDictionary.Add("o", o);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult AutoComplete(string f, string term) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.AutoComplete);
            callInfo.RouteValueDictionary.Add("f", f);
            callInfo.RouteValueDictionary.Add("term", term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
