CREATE TABLE [dbo].[ContentTags](
	[ContentId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_ContentTags] PRIMARY KEY CLUSTERED 
(
	[ContentId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_ContentTags_Contents] FOREIGN KEY([ContentId])
REFERENCES [dbo].[Contents] ([ContentId])
ON DELETE CASCADE
NOT FOR REPLICATION ,
 CONSTRAINT [FK_ContentTags_Tags] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tags] ([TagId])
ON DELETE CASCADE
NOT FOR REPLICATION 
)


