//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SongSearch.Web.Infrastructure.Storage.EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SongSearchLogContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SongSearchLogContext object using the connection string found in the 'SongSearchLogContext' section of the application configuration file.
        /// </summary>
        public SongSearchLogContext() : base("name=SongSearchLogContext", "SongSearchLogContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SongSearchLogContext object.
        /// </summary>
        public SongSearchLogContext(string connectionString) : base(connectionString, "SongSearchLogContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SongSearchLogContext object.
        /// </summary>
        public SongSearchLogContext(EntityConnection connection) : base(connection, "SongSearchLogContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentActionEvent> ContentActionEvents
        {
            get
            {
                if ((_ContentActionEvents == null))
                {
                    _ContentActionEvents = base.CreateObjectSet<ContentActionEvent>("ContentActionEvents");
                }
                return _ContentActionEvents;
            }
        }
        private ObjectSet<ContentActionEvent> _ContentActionEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SearchEvent> SearchEvents
        {
            get
            {
                if ((_SearchEvents == null))
                {
                    _SearchEvents = base.CreateObjectSet<SearchEvent>("SearchEvents");
                }
                return _SearchEvents;
            }
        }
        private ObjectSet<SearchEvent> _SearchEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserActionEvent> UserActionEvents
        {
            get
            {
                if ((_UserActionEvents == null))
                {
                    _UserActionEvents = base.CreateObjectSet<UserActionEvent>("UserActionEvents");
                }
                return _UserActionEvents;
            }
        }
        private ObjectSet<UserActionEvent> _UserActionEvents;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentActionEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentActionEvents(ContentActionEvent contentActionEvent)
        {
            base.AddObject("ContentActionEvents", contentActionEvent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SearchEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSearchEvents(SearchEvent searchEvent)
        {
            base.AddObject("SearchEvents", searchEvent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserActionEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserActionEvents(UserActionEvent userActionEvent)
        {
            base.AddObject("UserActionEvents", userActionEvent);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SongSearch.Web.Data.Model", Name="ContentActionEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentActionEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentActionEvent object.
        /// </summary>
        /// <param name="contentActionEventId">Initial value of the ContentActionEventId property.</param>
        /// <param name="contentActionEventDate">Initial value of the ContentActionEventDate property.</param>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="contentActionId">Initial value of the ContentActionId property.</param>
        /// <param name="contentId">Initial value of the ContentId property.</param>
        public static ContentActionEvent CreateContentActionEvent(global::System.Int64 contentActionEventId, global::System.DateTime contentActionEventDate, global::System.String sessionId, global::System.Int32 userId, global::System.Int32 contentActionId, global::System.Int32 contentId)
        {
            ContentActionEvent contentActionEvent = new ContentActionEvent();
            contentActionEvent.ContentActionEventId = contentActionEventId;
            contentActionEvent.ContentActionEventDate = contentActionEventDate;
            contentActionEvent.SessionId = sessionId;
            contentActionEvent.UserId = userId;
            contentActionEvent.ContentActionId = contentActionId;
            contentActionEvent.ContentId = contentId;
            return contentActionEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ContentActionEventId
        {
            get
            {
                return _ContentActionEventId;
            }
            set
            {
                if (_ContentActionEventId != value)
                {
                    OnContentActionEventIdChanging(value);
                    ReportPropertyChanging("ContentActionEventId");
                    _ContentActionEventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContentActionEventId");
                    OnContentActionEventIdChanged();
                }
            }
        }
        private global::System.Int64 _ContentActionEventId;
        partial void OnContentActionEventIdChanging(global::System.Int64 value);
        partial void OnContentActionEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ContentActionEventDate
        {
            get
            {
                return _ContentActionEventDate;
            }
            set
            {
                OnContentActionEventDateChanging(value);
                ReportPropertyChanging("ContentActionEventDate");
                _ContentActionEventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentActionEventDate");
                OnContentActionEventDateChanged();
            }
        }
        private global::System.DateTime _ContentActionEventDate;
        partial void OnContentActionEventDateChanging(global::System.DateTime value);
        partial void OnContentActionEventDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.String _SessionId;
        partial void OnSessionIdChanging(global::System.String value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentActionId
        {
            get
            {
                return _ContentActionId;
            }
            set
            {
                OnContentActionIdChanging(value);
                ReportPropertyChanging("ContentActionId");
                _ContentActionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentActionId");
                OnContentActionIdChanged();
            }
        }
        private global::System.Int32 _ContentActionId;
        partial void OnContentActionIdChanging(global::System.Int32 value);
        partial void OnContentActionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentId
        {
            get
            {
                return _ContentId;
            }
            set
            {
                OnContentIdChanging(value);
                ReportPropertyChanging("ContentId");
                _ContentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentId");
                OnContentIdChanged();
            }
        }
        private global::System.Int32 _ContentId;
        partial void OnContentIdChanging(global::System.Int32 value);
        partial void OnContentIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SongSearch.Web.Data.Model", Name="SearchEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SearchEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SearchEvent object.
        /// </summary>
        /// <param name="searchEventId">Initial value of the SearchEventId property.</param>
        /// <param name="searchEventDate">Initial value of the SearchEventDate property.</param>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="resultCount">Initial value of the ResultCount property.</param>
        /// <param name="queryString">Initial value of the QueryString property.</param>
        public static SearchEvent CreateSearchEvent(global::System.Int64 searchEventId, global::System.DateTime searchEventDate, global::System.String sessionId, global::System.Int32 userId, global::System.Int32 resultCount, global::System.String queryString)
        {
            SearchEvent searchEvent = new SearchEvent();
            searchEvent.SearchEventId = searchEventId;
            searchEvent.SearchEventDate = searchEventDate;
            searchEvent.SessionId = sessionId;
            searchEvent.UserId = userId;
            searchEvent.ResultCount = resultCount;
            searchEvent.QueryString = queryString;
            return searchEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SearchEventId
        {
            get
            {
                return _SearchEventId;
            }
            set
            {
                if (_SearchEventId != value)
                {
                    OnSearchEventIdChanging(value);
                    ReportPropertyChanging("SearchEventId");
                    _SearchEventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SearchEventId");
                    OnSearchEventIdChanged();
                }
            }
        }
        private global::System.Int64 _SearchEventId;
        partial void OnSearchEventIdChanging(global::System.Int64 value);
        partial void OnSearchEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SearchEventDate
        {
            get
            {
                return _SearchEventDate;
            }
            set
            {
                OnSearchEventDateChanging(value);
                ReportPropertyChanging("SearchEventDate");
                _SearchEventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SearchEventDate");
                OnSearchEventDateChanged();
            }
        }
        private global::System.DateTime _SearchEventDate;
        partial void OnSearchEventDateChanging(global::System.DateTime value);
        partial void OnSearchEventDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.String _SessionId;
        partial void OnSessionIdChanging(global::System.String value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResultCount
        {
            get
            {
                return _ResultCount;
            }
            set
            {
                OnResultCountChanging(value);
                ReportPropertyChanging("ResultCount");
                _ResultCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResultCount");
                OnResultCountChanged();
            }
        }
        private global::System.Int32 _ResultCount;
        partial void OnResultCountChanging(global::System.Int32 value);
        partial void OnResultCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QueryString
        {
            get
            {
                return _QueryString;
            }
            set
            {
                OnQueryStringChanging(value);
                ReportPropertyChanging("QueryString");
                _QueryString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QueryString");
                OnQueryStringChanged();
            }
        }
        private global::System.String _QueryString;
        partial void OnQueryStringChanging(global::System.String value);
        partial void OnQueryStringChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SongSearch.Web.Data.Model", Name="UserActionEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserActionEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserActionEvent object.
        /// </summary>
        /// <param name="userActionEventId">Initial value of the UserActionEventId property.</param>
        /// <param name="userActionEventDate">Initial value of the UserActionEventDate property.</param>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userActionId">Initial value of the UserActionId property.</param>
        public static UserActionEvent CreateUserActionEvent(global::System.Int64 userActionEventId, global::System.DateTime userActionEventDate, global::System.String sessionId, global::System.Int32 userId, global::System.Int32 userActionId)
        {
            UserActionEvent userActionEvent = new UserActionEvent();
            userActionEvent.UserActionEventId = userActionEventId;
            userActionEvent.UserActionEventDate = userActionEventDate;
            userActionEvent.SessionId = sessionId;
            userActionEvent.UserId = userId;
            userActionEvent.UserActionId = userActionId;
            return userActionEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserActionEventId
        {
            get
            {
                return _UserActionEventId;
            }
            set
            {
                if (_UserActionEventId != value)
                {
                    OnUserActionEventIdChanging(value);
                    ReportPropertyChanging("UserActionEventId");
                    _UserActionEventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserActionEventId");
                    OnUserActionEventIdChanged();
                }
            }
        }
        private global::System.Int64 _UserActionEventId;
        partial void OnUserActionEventIdChanging(global::System.Int64 value);
        partial void OnUserActionEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UserActionEventDate
        {
            get
            {
                return _UserActionEventDate;
            }
            set
            {
                OnUserActionEventDateChanging(value);
                ReportPropertyChanging("UserActionEventDate");
                _UserActionEventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserActionEventDate");
                OnUserActionEventDateChanged();
            }
        }
        private global::System.DateTime _UserActionEventDate;
        partial void OnUserActionEventDateChanging(global::System.DateTime value);
        partial void OnUserActionEventDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.String _SessionId;
        partial void OnSessionIdChanging(global::System.String value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserActionId
        {
            get
            {
                return _UserActionId;
            }
            set
            {
                OnUserActionIdChanging(value);
                ReportPropertyChanging("UserActionId");
                _UserActionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserActionId");
                OnUserActionIdChanged();
            }
        }
        private global::System.Int32 _UserActionId;
        partial void OnUserActionIdChanging(global::System.Int32 value);
        partial void OnUserActionIdChanged();

        #endregion
    
    }

    #endregion
    
}
